---

- hosts: all
  gather_facts: False
  connection: local

  tasks:

    - name: ping
      shell: ping -c 1 -w 2 8.8.8.8
      ignore_errors: true
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
